// This file is auto-generated by scripts/generate-plugins.ts
export default [
	{
		"text": "Integration",
		"link": "/plugins/integration/",
		"items": [
			{
				"text": "3rd party integration",
				"link": "/plugins/integration/3rd-party-integration/"
			},
			{
				"text": "Frameworks & build systems",
				"link": "/plugins/integration/frameworks-build-systems/"
			}
		],
		"collapsed": false
	},
	{
		"text": "Map interaction",
		"link": "/plugins/map-interactions/",
		"items": [
			{
				"text": "Bookmarked pan/zoom",
				"link": "/plugins/map-interactions/bookmarked-pan-zoom/"
			},
			{
				"text": "Events",
				"link": "/plugins/map-interactions/events/"
			},
			{
				"text": "Fullscreen controls",
				"link": "/plugins/map-interactions/fullscreen-controls/"
			},
			{
				"text": "Geolocation",
				"link": "/plugins/map-interactions/geolocation/"
			},
			{
				"text": "Interactive pan/zoom",
				"link": "/plugins/map-interactions/interactive-pan-zoom/"
			},
			{
				"text": "Layer switching controls",
				"link": "/plugins/map-interactions/layer-switching-controls/"
			},
			{
				"text": "Measurement",
				"link": "/plugins/map-interactions/measurement/"
			},
			{
				"text": "Minimaps & synced maps",
				"link": "/plugins/map-interactions/minimaps-synced-maps/"
			},
			{
				"text": "Mouse coordinates",
				"link": "/plugins/map-interactions/mouse-coordinates/"
			},
			{
				"text": "Print/export",
				"link": "/plugins/map-interactions/print-export/"
			},
			{
				"text": "User interface",
				"link": "/plugins/map-interactions/user-interface/"
			}
		],
		"collapsed": true
	},
	{
		"text": "Miscellaneous",
		"link": "/plugins/miscellaneous/",
		"items": [
			{
				"text": "Geocoding",
				"link": "/plugins/miscellaneous/geocoding/"
			},
			{
				"text": "Geoprocessing",
				"link": "/plugins/miscellaneous/geoprocessing/"
			},
			{
				"text": "Plugin collections",
				"link": "/plugins/miscellaneous/plugin-collections/"
			},
			{
				"text": "Routing",
				"link": "/plugins/miscellaneous/routing/"
			}
		],
		"collapsed": true
	},
	{
		"text": "Overlay data",
		"link": "/plugins/overlay-data/",
		"items": [
			{
				"text": "Data providers",
				"link": "/plugins/overlay-data/data-providers/"
			},
			{
				"text": "Dynamic/custom data loading",
				"link": "/plugins/overlay-data/dynamic-custom-data-loading/"
			},
			{
				"text": "Overlay data formats",
				"link": "/plugins/overlay-data/overlay-data-formats/"
			},
			{
				"text": "Synthetic overlays",
				"link": "/plugins/overlay-data/synthetic-overlays/"
			}
		],
		"collapsed": true
	},
	{
		"text": "Overlay display",
		"link": "/plugins/overlay-display/",
		"items": [
			{
				"text": "Clustering/Decluttering",
				"link": "/plugins/overlay-display/clustering-decluttering/"
			},
			{
				"text": "DataViz",
				"link": "/plugins/overlay-display/dataviz/"
			},
			{
				"text": "Heatmaps",
				"link": "/plugins/overlay-display/heatmaps/"
			},
			{
				"text": "Markers & renderers",
				"link": "/plugins/overlay-display/markers-renderers/"
			},
			{
				"text": "Overlay animations",
				"link": "/plugins/overlay-display/overlay-animations/"
			}
		],
		"collapsed": true
	},
	{
		"text": "Interaction with geometries/features",
		"link": "/plugins/overlay-interaction/",
		"items": [
			{
				"text": "Area/overlay selection",
				"link": "/plugins/overlay-interaction/area-overlay-selection/"
			},
			{
				"text": "Edit geometries",
				"link": "/plugins/overlay-interaction/edit-geometries/"
			},
			{
				"text": "Search & popups",
				"link": "/plugins/overlay-interaction/search-popups/"
			},
			{
				"text": "Time & elevation",
				"link": "/plugins/overlay-interaction/time-elevation/"
			}
		],
		"collapsed": true
	},
	{
		"text": "Tile & image layers",
		"link": "/plugins/tile-image-layers/",
		"items": [
			{
				"text": "Basemap formats",
				"link": "/plugins/tile-image-layers/basemap-formats/"
			},
			{
				"text": "Basemap providers",
				"link": "/plugins/tile-image-layers/basemap-providers/"
			},
			{
				"text": "Non-map base layers",
				"link": "/plugins/tile-image-layers/non-map-base-layers/"
			},
			{
				"text": "Tile/image display",
				"link": "/plugins/tile-image-layers/tile-image-display/"
			},
			{
				"text": "Tile Load",
				"link": "/plugins/tile-image-layers/tile-load/"
			},
			{
				"text": "Vector tiles",
				"link": "/plugins/tile-image-layers/vector-tiles/"
			}
		],
		"collapsed": true
	}
];
